/*const promesa = new Promise((resolve,reject) => {
    const numeroAleatorio = Math.random();
}*/

//TRY - CATCH - FINALLY
/*
try{
    let numeroA= 21;
    let numeroB = 75;
    let resultado = numeroA * numeroB;
    console.log("Intento hacer algo")
}
catch(error){
    console.error("Ocurrio un error inesperado",error);
}
finally{
    console.warn("Este mensaje lo ver√°s siempre");
}*/

//Asincronismo: el programa no se detiene mientras espera una respuesta de otra tarea
//Se usan funciones como CALLBACK

//ASYNC - AWAIT

//1:23:00 repaso

